const page = () => {
  return (
    <article className="w-full mx-auto flex flex-col justify-center mt-4">
      <h2 className="text-4xl font-bold my-4 text-start">Privacy Monal App {'≥'} 6.0.0</h2>
      <h3 className="text-2xl font-bold my-4 text-start">TLDR</h3>
      <div className="prose dark:prose-dark text-justify text-lg">
        <ul className="list-inside list-disc my-4">
          <li>
            We <b>never</b> see your messages.
          </li>
          <li>
            We <b>do not</b> know who you are chatting with.
          </li>
          <li>
            We <b>can not</b> identify a user.
          </li>
          <li>
            We can see your XMPP domain and a Monal specific unique device id every time you receive
            a push message
          </li>
          <li>
            We see your IP addresses if you are on a call and your XMPP server does not provide a
            STUN or TURN server.
          </li>
          <li>We may see your contact’s IP address if you are using our TURN server.</li>
        </ul>
        <h3 className="text-2xl font-bold my-4 text-start">Structure</h3>
        <p>
          The App Monal may interact with Monal servers to support Push messages or if you are
          establishing a call with a contact but your XMPP Server does neither provide a STUN nor a
          TURN server.
        </p>
        <br />
        <p>
          Our privacy details are structured as follows. First, we would like to give you a short
          introduction how Monal is handling push messages to ensure a pleasant user experience. We
          will then briefly explain VoIP calls and its privacy implications. Afterwards we like to
          inform you how we are using crash and usage reports, logs and GDPR Subject Access Requests
          (SAR).
        </p>
        <h3 className="text-2xl font-bold my-4 text-start">Push</h3>
        <p>
          App Resources are very limited on iOS and macOS. Monal for example can only run a limited
          time in the background after a user either locked the screen or switched the app. Hence,
          apps on iOS and macOS can not simply keep a connection to your XMPP server open 24/7 to
          inform you about new messages. To overcome these limitations your XMPP server can request
          our push server to send push messages to your device through Apple. With these push
          messages we can request Apple to wake up Monal on your device. Once it is woken up it has
          about 30 seconds to connect to your XMPP server, fetch all new messages and show a push
          notification for these new messages, if needed.
        </p>
        <h3 className="text-2xl font-bold my-4 text-start">How push works</h3>
        <p>
          Every time that Monal loggs in at your XMPP servers, it asks your server to inform our
          push server once you receive an XMPP message while Monal is closed/disconnected. To do
          this, we request a Monal specific push token from Apple and provide this token to your
          XMPP server. Using this Monal specific push token your XMPP server can instruct our push
          server to send push messages via Apples push system to wake up the app on your device.
        </p>
        <br />
        <p>
          Once push messages are enabled for your Monal instance on all your XMPP servers, your XMPP
          servers will open a encrypted server to server (s2s) connection to one of our push
          servers. Using this s2s connection your XMPP servers will then be able to talk to our push
          servers. To wake up your Monal instance your XMPP servers send us:
        </p>
        <ul className="list-inside list-disc my-4">
          <li>Your unique Monal specific push token that was generated by Apple</li>
          <li>The domain of the XMPP server that you are using</li>
        </ul>
        <h3 className="text-2xl font-bold my-4 text-start">Push</h3>
        <ul className="list-inside list-disc my-4">
          <li>
            We <b>never</b> see your messages.
          </li>
          <li>
            We <b>do not</b> know who you are chatting with.
          </li>
          <li>
            We could <b>only</b> ever track what XMPP domains a push token is/was using.
          </li>
          <li>
            We <b>can not</b> identify a user.
          </li>
        </ul>
        <h3 className="text-2xl font-bold my-4 text-start">Push-Servers</h3>
        <p>We currently provide the following independent push server regions:</p>
        <ul className="list-inside list-disc my-4">
          <li>Europe</li>
          <li>
            Alpha (based in Europe, only used for debugging with higher log levels, not for
            production use)
          </li>
        </ul>
        <p>
          <b>Note:</b> Our previously used US push region was unfortunately shutdown{' '}
          <u>due to fosshost ceasing operation.</u>
        </p>
        <h3 className="text-2xl font-bold my-4 text-start">How to change push region</h3>
        <blockquote className="border-l-4 border-l-black-500 pl-4 py-2 my-2">
          <ul className="list-inside list-decimal">
            <li>Open Monal</li>
            <li>Open up the settings menu in the upper left corner (gearwheel)</li>
            <li>Open the Notifications menu</li>
            <li>Scroll down</li>
            <li>Select a region</li>
          </ul>
        </blockquote>
        <h3 className="text-2xl font-bold my-4 text-start">Push server regions</h3>
        <p>
          If you are an XMPP server administrator, and you restricted s2s connections, please allow
          s2s to all our regions.
        </p>
        <table className="w-full border border-gray-300 shadow-md my-4">
          <thead>
            <tr>
              <th className="px-4 py-2 border">Region</th>
              <th className="px-4 py-2 border">Hostname</th>
              <th className="px-4 py-2 border">Notice</th>
            </tr>
          </thead>
          <tbody>
            <tr className="border-b hover:bg-gray-100">
              <td className="px-4 py-2 border">Europe</td>
              <td className="px-4 py-2 border">eu.prod.push.monal-im.org</td>
            </tr>
          </tbody>
        </table>
        <h3 className="text-2xl font-bold my-4 text-start">Push server locations</h3>
        <table className="w-full border border-gray-300 shadow-md my-4">
          <thead>
            <tr>
              <th className="px-4 py-2 border">Name</th>
              <th className="px-4 py-2 border">Region</th>
              <th className="px-4 py-2 border">Hoster</th>
              <th className="px-4 py-2 border">Location</th>
              <th className="px-4 py-2 border">Notice</th>
            </tr>
          </thead>
          <tbody>
            <tr className="border-b hover:bg-gray-100">
              <td className="px-4 py-2 border">s1.eu.prod.push.monal-im.org </td>
              <td className="px-4 py-2 border">Europe</td>
              <td className="px-4 py-2 border">Hetzner</td>
              <td className="px-4 py-2 border">Finland</td>
            </tr>
            <tr className="border-b hover:bg-gray-100">
              <td className="px-4 py-2 border">s2.eu.prod.push.monal-im.org </td>
              <td className="px-4 py-2 border">Europe</td>
              <td className="px-4 py-2 border">PHP-Friends</td>
              <td className="px-4 py-2 border">Germany</td>
            </tr>
          </tbody>
        </table>
        <h3 className="text-2xl font-bold my-4 text-start">VoIP (STUN / TURN)</h3>
        <div className="prose dark:prose-dark text-justify text-lg">
          <p>
            With Monal 6.0 we introduced VoIP support. To establish the connection between you and
            the remote party (the remote contact) Monal utilizes STUN and TURN. In general STUN
            (Session Traversal Utilities for NAT) is used to allow a VoIP call even when you are
            behind firewalls.
          </p>
          <br />
          <p>
            Calls established using only STUN will directly exchange packets (P2P) between you and
            your contact. Hence, your contact may see your IP address. If you do not want your
            contact to see your IP Address while being on a call, disable P2P connection in Monal’s
            privacy settings. Once disabled Monal tries to establish the call using a TURN
            (Traversal Using Relays around NAT) server.
          </p>
          <br />
          <p>
            <b>Note:</b> Not all XMPP servers currently provide STUN and TURN servers. If your XMPP
            server does not provide STUN and TURN servers, Monal may use our fallback servers. These
            fallback servers provide both STUN and TURN. You can disable Monal to use these fallback
            turn servers. Please note, that we may disable our fallback STUN and TURN servers at any
            time, if too many users are using them.
          </p>
          <br />
          <p>If you use our fallback servers we will see:</p>
          <ul className="list-inside list-disc my-4">
            <li>Your IP Addresses</li>
            <li>The IPs of your contact or the IPs of their TURN-Server</li>
            <li>The duration of the call</li>
          </ul>
          <p>
            We will <b>not</b> see the contents of that call, because these are E2E encrypted.
          </p>
          <h3 className="text-2xl font-bold my-4 text-start">Crash reports and app usage</h3>
          <p>
            Monal does track crashes and usage data anonymously using the tools provided by Apple.
            This is opt-in only and controlled by iOS and macOS global settings. If a user decides
            not to send any data to developers, no crash logs are sent to Monal developers.
          </p>
          <h3 className="text-2xl font-bold my-4 text-start">Logs</h3>
          <p>
            Your local device will contain a log file with all sent and received raw XMPP messages
            as well as debug logs. It does contain sensitive personal data! This file will never be
            transferred to us, except if you explicitly (manually) send it to us (e.g., via mail).
          </p>
          <h3 className="text-2xl font-bold my-4 text-start">GDPR Subject Access Requests (SAR)</h3>
          <p>
            European GDPR allows users to request a copy of all data retained about them. Starting
            with Monal 5.2.0 we no longer see your JIDs<u>(username@domain.tld)</u> in our push
            servers. We therefore are not able to send you retained data related to your JID. We
            furthermore are unable to provide your retained data related to your unique push token
            because we have no way to verify that Apple issued you a provided token. If you have
            questions regarding GDPR, please send us a mail to <u>info@monal-im.org</u>.
          </p>
        </div>
      </div>
    </article>
  );
};

export default page;
